### ISSUE TITLE
Interaction with Lookyloo

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/url-abuse#12]
Hey,

I saw that the project can interact with lookyloo, but in case if I have a lookyloo server, and want to interact with it, is it possible to configure the remote url of lookyloo ?

Best regards,

**Comment by Rafiot** [comment]
So interaction is a big word: it sends the URL to lookyloo via the (undocumented) API, the API returns the UUID, and a link with that UUID to the lookyloo event is added on the urlabuse page.
