### ISSUE TITLE
Missing JS files?

### ISSUE THREAD

**Issue by faysalam** [CIRCL/url-abuse#6]
Hello,

Every time I try to submit a url to be analyzed I receive these errors:

127.0.0.1 - - [02/May/2017 12:31:20] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/bootstrap/css/bootstrap.min.css?bootstrap=3.3.7.1.dev1 HTTP/1.1" 304 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/angular.min.js HTTP/1.1" 404 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/ui-bootstrap-tpls.min.js HTTP/1.1" 404 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/main.js HTTP/1.1" 304 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/bootstrap/jquery.min.js?bootstrap=3.3.7.1.dev1 HTTP/1.1" 304 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/bootstrap/js/bootstrap.min.js?bootstrap=3.3.7.1.dev1 HTTP/1.1" 304 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/ui-bootstrap-tpls.min.js HTTP/1.1" 404 -
127.0.0.1 - - [02/May/2017 12:31:20] "GET /static/ajax-loader.gif HTTP/1.1" 304 - 

Are these files missing? because I can't even see them in this hithub page?

**Comment by Rafiot** [comment]
In order to not add lots of files to the repository, there is a script to download them: https://github.com/CIRCL/url-abuse/blob/master/update_deps.sh
